baseURL = 'https://v3-worx.be/'
# baseURL = 'https://v3worx.netlify.app/'
languageCode = 'nl-be'
title = 'V3-Worx'
theme = 'ananke'

DefaultContentLanguage = "nl"
SectionPagesMenu = "main"
pagination.pagerSize  = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.nl]
title = "V3-Worx"
weight = 1
contentDir = "content/nl"
[languages.fr]
title = "V3-Worx"
weight = 2
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  mainSections = ["realisaties"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/v3worx"

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "facebook",
  "instagram",
  "linkedin"
]
[params.ananke.social.facebook]
  username = "v3worx"
[params.ananke.social.linkedin]
  username = "v3-worx" 
  link = "https://www.linkedin.com/company/v3-worx"
[params.ananke.social.instagram]
  username = "v3worx"

[menu]
  [[menu.main]]
    identifier = "aanbod"
    name = "Aanbod"
    url = "/aanbod/"
    weight = 10

  [[menu.main]]
    identifier = "werkwijze"
    name = "Werkwijze"
    url = "/werkwijze/"
    weight = 20

  [[menu.main]]
    identifier = "realisaties"
    name = "Realisaties"
    url = "/realisaties/"
    weight = 30

  [[menu.main]]
    identifier = "ons-team"
    name = "Ons team"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
